# Generated by Django 5.2.7 on 2025-10-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_role_sellerprofile_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedpricelisting',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
