# Generated by Django 5.2.7 on 2025-11-01 22:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedpricelisting',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedpricelisting',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99.99'))]),
        ),
        migrations.AddField(
            model_name='fixedpricelisting',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
