# Generated by Django 5.2.7 on 2025-11-12 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_payment_stripe_transfer_id_and_more'),
    ]

    operations = [
        # First, remove the old unique_together constraint
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        # Then add the new product field
        migrations.AddField(
            model_name='conversation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.product'),
        ),
        # Remove the old order field
        migrations.RemoveField(
            model_name='conversation',
            name='order',
        ),
        # Finally, add the new unique_together constraint with product
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('buyer', 'seller', 'product')},
        ),
    ]
