# Generated by Django 5.2.7 on 2025-11-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_conversation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='business_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
