# Generated by Django 5.2.7 on 2025-11-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sellerprofile_business_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_profiles', to='api.address'),
        ),
    ]
