# Generated by Django 5.2.7 on 2025-11-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_orderitem_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_failed', 'Payment Failed'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered (Deprecated - Use Shipped)'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
    ]
